In [1]:
# numpy is the library that allows for the use of arrays and matrices in python 
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [3]:
type(a)

numpy.ndarray

BASIC OPERATIONS OF ARRAY

In [4]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [5]:
# creating a 2D array
a =  np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]


In [6]:
# creating 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
print(b.shape)

(2, 2, 2)


In [8]:
print(a.ndim)

2


In [9]:
print(b.ndim)

3


In [10]:
print(a.dtype)

int64


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [13]:
np.random.randint(10,30, size=(3,3))

array([[29, 14, 14],
       [20, 21, 13],
       [21, 22, 15]], dtype=int32)

In [14]:
x = np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])
y = np.array([[1,8,7],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 7]
 [3 7 2]
 [2 5 3]]


In [15]:
print(x*y)

[[ 7 16 21]
 [ 6 35  4]
 [ 6 25  3]]


In [16]:
print(x.dot(y)) #matrix multiplication

[[19 85 62]
 [21 61 30]
 [20 64 34]]


In [17]:
print(x@y)

[[19 85 62]
 [21 61 30]
 [20 64 34]]


In [18]:
x.prod() # It give multiplication of the elements of the array

np.int64(12600)

In [19]:
x.mean() # it gives the mean of all elements of the array

np.float64(3.3333333333333335)

In [20]:
x.mean(axis=0) # it gives the mean of each columns

array([4., 4., 2.])

In [21]:
x.mean(axis=1) # it gives the mean of each row

array([4., 3., 3.])

In [22]:
print(x.sum()) # it gives the sum of all the elements of the array
print(x.var()) # it gives the variance of all the elements of the array
print(x.std()) # it gives the standard derivation of all the elements of the array

30
3.3333333333333335
1.8257418583505538


In [23]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(a,25)) # it gives the 25th percentile of the array
print(np.percentile(a,50)) # it gives the 50th percentile of the array
print(np.percentile(a,75)) # it gives the 75th percentile of the array

3.0
5.0
7.0


In [24]:
arr = np.random.randint(10,50, size=(4,4))
print(arr)

[[19 45 30 27]
 [20 21 35 34]
 [42 12 13 22]
 [19 45 47 29]]


In [25]:
print('8x2')
print(arr.reshape(8,2))

8x2
[[19 45]
 [30 27]
 [20 21]
 [35 34]
 [42 12]
 [13 22]
 [19 45]
 [47 29]]


In [26]:
print(arr.reshape(2,8))

[[19 45 30 27 20 21 35 34]
 [42 12 13 22 19 45 47 29]]


In [27]:
print(x)

[[7 2 3]
 [2 5 2]
 [3 5 1]]


In [28]:
print(x[1]) #INDEXING
print(x[1,1])

[2 5 2]
5


In [29]:
print(x[:3]) # SLICING
print(x[2:])

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[3 5 1]]
