In [2]:
# numpy is the library that allows for the use of arrays and matrices in python 
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 2 3]
[4 5 6]


In [4]:
type(a)

numpy.ndarray

BASIC OPERATIONS OF ARRAY

In [5]:
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [6]:
# creating a 2D array
a =  np.array([[1,2],[3,4]])
print(a)


[[1 2]
 [3 4]]


In [10]:
# creating 3D array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [11]:
print(b.shape)

(2, 2, 2)


In [12]:
print(a.ndim)

2


In [13]:
print(b.ndim)

3


In [14]:
print(a.dtype)

int64


In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [17]:
np.random.randint(10,30, size=(3,3))

array([[25, 10, 16],
       [25, 27, 12],
       [14, 15, 19]], dtype=int32)

In [18]:
x = np.array([[7,2,3],
            [2,5,2],
            [3,5,1]])
y = np.array([[1,8,7],
              [3,7,2],
              [2,5,3]])
print(x)
print(y)

[[7 2 3]
 [2 5 2]
 [3 5 1]]
[[1 8 7]
 [3 7 2]
 [2 5 3]]
